### ISSUE TITLE
SSHExecutor returns ModuleNotFoundError for `cloudpickle` despite being installed in remote machine

### ISSUE THREAD

**Issue by venkatBala** [AgnostiqHQ/covalent-ssh-plugin#12]
SSHExecutor yields `ModuleNotFoundError` for `cloudpickle`. To reproduce this error, run the quantum machine learning tutorial `doc/source/tutorials/machine_learning/classical_quantum_svm.ipynb` under `covalent`

**Comment by Emmanuel289** [comment]
A workaround for this issue is to specify the python path of the active Conda environment in the remote machine when instantiating the SSH executor. 
```
ssh_exec = SSHExecutor(
    username="",
    hostname="",
    remote_dir="/tmp/covalent",
    ssh_key_file="/Path/to/key_file",
    python3_path="/Path/to/python3"
)
```

**Comment by AlejandroEsquivel** [comment]
If this issue is encountered it is very likely an issue with resolving which python binary is to be used, particularly when using virtualenvs.

If using conda the recommended action is to use the `conda_env` parameter to reference the named conda environment that was created (this is now supported as of https://github.com/AgnostiqHQ/covalent-ssh-plugin/pull/28)

Otherwise using the `python3_path` (now called `python_path`) to point to the exact python binary to be used resolves the issue.

**Comment by kessler-frost** [comment]
@venkatBala @Emmanuel289 This issue should now be resolved. Can you guys confirm if this still exists? Now you can specify the conda environment with `conda_env`, so no need to mess around with python paths.
